create table if not exists public.cors_origins (
  id bigint generated by default as identity primary key,
  origin text not null unique,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists cors_origins_enabled_idx
  on public.cors_origins (enabled);

alter table public.cors_origins enable row level security;

-- The server uses SUPABASE_SERVICE_ROLE_KEY, so no public policies are required.
